export * from './auth.schema';
export * from './role.schema';
export * from './school.schema';
export * from './academic-year.schema';
export * from './grade.schema';
export * from './student.schema';
export * from './parent.schema';
export * from './user.schema';
export * from './fee-type.schema';
