export const API_CONFIG = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api/v1',
  TIMEOUT: 30000,
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/Auth/login',
    REGISTER: '/Auth/register',
    REFRESH_TOKEN: '/Auth/refresh-token',
    ME: '/Auth/me',
    CHANGE_PASSWORD: '/Auth/change-password',
    OTP_REQUEST: '/Auth/otp/request',
    OTP_VERIFY: '/Auth/otp/verify',
    CHANGE_PHONE_REQUEST: '/Auth/me/phone/request',
    CHANGE_PHONE_VERIFY: '/Auth/me/phone/verify',
  },
  ONBOARDING: {
    PARENT: '/Onboarding/parent',
    PARENT_COMPLETE: '/Onboarding/parent/complete',
  },
  USERS: {
    LIST: '/Users',
    DETAIL: (id: string) => `/Users/${id}`,
  },
  ROLES: {
    LIST: '/Roles',
    DETAIL: (id: string) => `/Roles/${id}`,
    PERMISSIONS: (id: string) => `/Roles/${id}/permissions`,
    ASSIGN_USER: (roleId: string, userId: string) => `/Roles/${roleId}/users/${userId}`,
    REMOVE_USER: (roleId: string, userId: string) => `/Roles/${roleId}/users/${userId}`,
  },
  PERMISSIONS: {
    LIST: '/Permissions',
  },
  SCHOOLS: {
    LIST: '/Schools',
    DETAIL: (id: string) => `/Schools/${id}`,
    MY_SCHOOL: '/Schools/my-school',
    STATUS: (id: string) => `/Schools/${id}/status`,
    SETTINGS: (id: string) => `/Schools/${id}/settings`,
    ADMINS: (id: string) => `/Schools/${id}/admins`,
    REMOVE_ADMIN: (id: string, userId: string) => `/Schools/${id}/admins/${userId}`,
    SETUP_STATUS: (id: string) => `/Schools/${id}/setup-status`,
    DASHBOARD: (id: string) => `/Schools/${id}/dashboard`,
    COMPLETE_SETUP: (id: string) => `/Schools/${id}/complete-setup`,
    STAFF: (id: string) => `/Schools/${id}/staff`,
    INVITE: (id: string) => `/Schools/${id}/invite`,
  },
  ACADEMIC_YEARS: {
    LIST: '/AcademicYears',
    DETAIL: (id: string) => `/AcademicYears/${id}`,
    ACTIVATE: (id: string) => `/AcademicYears/${id}/activate`,
    COMPLETE: (id: string) => `/AcademicYears/${id}/complete`,
    SET_CURRENT: (id: string) => `/AcademicYears/${id}/set-current`,
    LINK_SCHOOL: (id: string) => `/AcademicYears/${id}/link-school`,
  },
  GRADES: {
    LIST: '/Grades',
    DETAIL: (id: string) => `/Grades/${id}`,
    STATUS: (id: string) => `/Grades/${id}/status`,
    STATS: (id: string) => `/Grades/${id}/stats`,
    SECTIONS: (gradeId: string) => `/Grades/${gradeId}/sections`,
    SECTION: (gradeId: string, sectionId: string) => `/Grades/${gradeId}/sections/${sectionId}`,
    SECTION_STATUS: (gradeId: string, sectionId: string) => `/Grades/${gradeId}/sections/${sectionId}/status`,
  },
  STUDENTS: {
    LIST: '/Students',
    DETAIL: (id: string) => `/Students/${id}`,
    STATUS: (id: string) => `/Students/${id}/status`,
    ENROLL_PARENT: (studentId: string) => `/Students/${studentId}/parents/enroll`,
    PARENTS: (studentId: string) => `/Students/${studentId}/parents`,
    PARENT: (studentId: string, parentUserId: string) => `/Students/${studentId}/parents/${parentUserId}`,
  },
  FEE_TYPES: {
    LIST: '/FeeTypes',
    DETAIL: (id: string) => `/FeeTypes/${id}`,
    STATUS: (id: string) => `/FeeTypes/${id}/status`,
  },
  FEE_STRUCTURES: {
    LIST: '/FeeStructures',
    DETAIL: (id: string) => `/FeeStructures/${id}`,
    STATUS: (id: string) => `/FeeStructures/${id}/status`,
  },
  FEE_INSTANCES: {
    LIST: '/FeeInstances',
    DETAIL: (id: string) => `/FeeInstances/${id}`,
    DISCOUNT: (id: string) => `/FeeInstances/${id}/discount`,
    WAIVE: (id: string) => `/FeeInstances/${id}/waive`,
    CANCEL: (id: string) => `/FeeInstances/${id}/cancel`,
    DETECT_OVERDUE: '/FeeInstances/detect-overdue',
  },
  PARENTS: {
    LIST: '/Parents',
    DETAIL: (parentUserId: string) => `/Parents/${parentUserId}`,
    CHILDREN: '/Parents/children',
    MY_FEES: '/Parents/my-fees',
    MY_FEE_ITEMS: '/Parents/my-fees/items',
    MY_ORDERS: '/Parents/my-orders',
    ME_DASHBOARD: '/Parents/me/dashboard',
    ME_CHILD_DETAIL: (childId: string) => `/Parents/me/children/${childId}`,
    ME_MARK_FEE_TYPE_SEEN: (feeTypeId: string) => `/Parents/me/fee-types/${feeTypeId}/mark-seen`,
    DASHBOARD: (parentUserId: string) => `/Parents/${parentUserId}/dashboard`,
    CHILDREN_FOR_PARENT: (parentUserId: string) => `/Parents/${parentUserId}/children`,
    FEES: (parentUserId: string) => `/Parents/${parentUserId}/fees`,
    FEE_DASHBOARD: (parentUserId: string) => `/Parents/${parentUserId}/fees/dashboard`,
    ORDERS: (parentUserId: string) => `/Parents/${parentUserId}/orders`,
  },
  NOTIFICATIONS: {
    LIST: '/Notifications',
    UNREAD_COUNT: '/Notifications/unread-count',
    MARK_READ: (id: string) => `/Notifications/${id}/read`,
    MARK_ALL_READ: '/Notifications/read-all',
    SEND: '/Notifications/send',
    BULK_SEND: '/Notifications/bulk-send',
    DETAIL: (id: string) => `/Notifications/${id}`,
    RECIPIENTS: (id: string) => `/Notifications/${id}/recipients`,
    SENT: '/Notifications/sent',
  },
  PLANS: {
    LIST: '/Plans',
    DETAIL: (id: string) => `/Plans/${id}`,
    TOGGLE_STATUS: (id: string) => `/Plans/${id}/toggle-status`,
    ASSIGN_SCHOOL: (planId: string, schoolId: string) => `/Plans/${planId}/schools/${schoolId}`,
    CANCEL_SUBSCRIPTION: (schoolId: string) => `/Plans/schools/${schoolId}/subscription`,
  },
  FILES: {
    LIST: '/Files',
    DETAIL: (id: string) => `/Files/${id}`,
    UPLOAD: '/Files/upload',
    DOWNLOAD: (id: string) => `/Files/${id}/download`,
    ACCESS_LOGS: (id: string) => `/Files/${id}/access-logs`,
    CATEGORIES: '/Files/categories',
    CATEGORY_DETAIL: (id: string) => `/Files/categories/${id}`,
  },
  PRODUCTS: {
    LIST: '/Products',
    DETAIL: (id: string) => `/Products/${id}`,
    STATUS: (id: string) => `/Products/${id}/status`,
  },
  WALLETS: {
    LIST: '/Wallets',
    DETAIL: (id: string) => `/Wallets/${id}`,
    STATUS: (id: string) => `/Wallets/${id}/status`,
    TOP_UP_CASH: (id: string) => `/Wallets/${id}/top-up/cash`,
    TOP_UP_GATEWAY: (id: string) => `/Wallets/${id}/top-up/gateway`,
    TRANSACTIONS: (id: string) => `/Wallets/${id}/transactions`,
  },
  FEE_INSTANCE_PAYMENTS: {
    PAY_WITH_WALLET: (id: string) => `/FeeInstances/${id}/pay/wallet`,
    PAY_WITH_GATEWAY: (id: string) => `/FeeInstances/${id}/pay/gateway`,
    PAY_WITH_CASH: (id: string) => `/FeeInstances/${id}/pay/cash`,
  },
  ORDERS: {
    LIST: '/Orders',
    DETAIL: (id: string) => `/Orders/${id}`,
    RECEIPT: (id: string) => `/Orders/${id}/receipt`,
  },
  REPORTS: {
    CASH_RECONCILIATION: '/Reports/cash-reconciliation',
  },
} as const;
